version: "3.8"
services:
  api:
    build: ./sentence-builder-backend
    container_name: api_container
    ports:
      - '5000:5000'
  frontend:
    build: ./sentence-builder-frontend
    container_name: app_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true